//! Cluster-overlay release image-push step.
//!
//! Three pre-lift sibling sites across `commands/{kenshi,kenshi_agent,nix_builder}.rs`
//! each restated the same twelve-positional-argument [`push::execute`]
//! invocation byte-identically (modulo the `(image_path, registry, retries,
//! token)` runtime quartet) followed by `.await?` and a trailing
//! `println!()` blank-line separator that closes the "Push Image" step
//! banner:
//!
//! ```text
//! push::execute(
//!     image_path,
//!     registry.clone(),
//!     vec![], // tags - will be generated by auto_tags
//!     true,   // auto_tags
//!     "amd64".to_string(),
//!     retries,
//!     token,
//!     false,         // push_attic
//!     String::new(), // attic_cache
//!     None,          // update_kustomization_path
//!     false,         // commit_kustomization
//! )
//! .await?;
//! println!();
//! ```
//!
//! Three occurrences of an identical twelve-slot argument tuple past
//! THEORY §VI.1's three-is-a-law threshold, on a downstream API whose
//! signature has already grown once (the `commit_kustomization` slot
//! was appended after the initial `update_kustomization_path` boolean);
//! a further slot appended tomorrow would silently misalign all three
//! call sites (they are positional, not named) until each is audited
//! separately. This module is the law-redeeming extraction: the five
//! load-bearing default slots
//!
//! - `Vec::new()` explicit-tags list (deferred to `auto_tags`),
//! - `arch = "amd64"`,
//! - `push_attic = false` (cluster-overlay releases stage through GHCR
//!   directly rather than the Attic side-channel),
//! - `attic_cache = ""` (unused when `push_attic = false`),
//! - `update_kustomization_path = None` (the release pipeline updates
//!   each cluster's overlay in a SEPARATE step per cluster, never
//!   inline with the push), and
//! - `commit_kustomization = false`
//!
//! now live at ONE typed boundary. Each pre-lift flow passes only the
//! four runtime-varying arguments `(image_path, registry, retries, token)`
//! and inherits the shared defaults, the auto-tag / amd64 arch pair, the
//! trailing blank-line separator, and — most importantly — a compile-time
//! failure surface that captures ALL three sites at once when
//! [`push::execute`] grows a new positional slot.
//!
//! Peer of `commands/cluster_overlay_release_preamble.rs` (the head-of-
//! release-workflow release-banner + tag-computation primitive) and
//! `commands/release_commit.rs` (the tail-of-release-workflow commit-and-
//! push primitive) — same three-file consumer census, same
//! `cluster_overlay_release_*` naming discipline, same
//! `push_release_image_amd64_auto_tag` verb-forward function-naming
//! shape.

use anyhow::Result;

use crate::commands::push;

/// Push a release image to `registry` using auto-generated
/// `amd64-<sha>` / `amd64-latest` tags via [`push::execute`], then emit
/// the fleet-standard blank-line separator that closes the "Push Image"
/// step of a cluster-overlay release workflow.
///
/// The six load-bearing defaults — explicit-tag list empty (deferred to
/// `auto_tags = true`), arch `"amd64"`, `push_attic = false`,
/// `attic_cache = ""`, `update_kustomization_path = None`, and
/// `commit_kustomization = false` — are pinned here so a future
/// signature change on [`push::execute`] (a new positional slot, a
/// swap of two adjacent bool flags, a rename of the arch-string
/// convention) flows to all three cluster-overlay release flows from
/// one edit; the pre-lift shape would have silently misaligned the
/// three positional 12-tuple call sites on such a change.
///
/// The trailing `println!()` is the same blank-line separator the pre-lift
/// stanzas each spelled inline after `.await?`; it renders the workflow-
/// step boundary between "Push Image" and the following "Update cluster
/// kustomization" step, matching the fleet-standard step-boundary
/// separator convention.
///
/// # Examples
///
/// ```ignore
/// // Pre-lift (repeated verbatim across kenshi.rs, kenshi_agent.rs,
/// // nix_builder.rs):
/// push::execute(
///     image_path,
///     registry.clone(),
///     vec![], // tags - will be generated by auto_tags
///     true,   // auto_tags
///     "amd64".to_string(),
///     retries,
///     token,
///     false,         // push_attic
///     String::new(), // attic_cache
///     None,          // update_kustomization_path
///     false,         // commit_kustomization
/// )
/// .await?;
/// println!();
///
/// // Post-lift:
/// crate::commands::cluster_overlay_release_push_step::push_release_image_amd64_auto_tag(
///     image_path,
///     registry.clone(),
///     retries,
///     token,
/// )
/// .await?;
/// ```
pub async fn push_release_image_amd64_auto_tag(
    image_path: String,
    registry: String,
    retries: u32,
    token: Option<String>,
) -> Result<()> {
    push::execute(
        image_path,
        registry,
        Vec::new(),
        true,
        "amd64".to_string(),
        retries,
        token,
        false,
        String::new(),
        None,
        false,
    )
    .await?;
    println!();
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    // Caller shield: the pre-lift twelve-argument `push::execute(...)`
    // stanza carried a distinctive marker comment on its third
    // positional argument — `vec![], // tags - will be generated by
    // auto_tags` — that appeared VERBATIM across all three pre-lift
    // sites and NOWHERE else in the crate. Post-lift the marker
    // string must vanish from every `commands/*.rs` source: the
    // three pre-lift stanzas are gone, and any future call site
    // that reaches for the same twelve-tuple shape by copy-paste
    // (rather than through the typed primitive) will drag the marker
    // along and trip this shield.
    //
    // The needle is anchored on the marker's exact byte sequence so a
    // future variant that spells the comment differently ("tags -
    // auto_tags will populate", "tags - see auto_tags") is out of
    // scope; the shield's positive-half delegation-count assertion
    // (below) forces future variants of the SAME twelve-tuple shape
    // through the primitive too.
    #[test]
    fn no_command_module_still_spells_prelift_auto_tag_marker_comment() {
        // Assemble the marker needle from two-substring halves at
        // runtime so this test file's own source does not contain
        // the marker as one contiguous literal — otherwise the
        // shield would self-hit on the very `line.contains(marker)`
        // call below. The runtime join yields the exact pre-lift
        // marker byte sequence.
        let marker: String = ["tags - will be", "generated by auto_tags"].join(" ");
        let commands_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src")
            .join("commands");
        let mut offenders: Vec<(PathBuf, usize, String)> = Vec::new();
        for entry in std::fs::read_dir(&commands_dir).unwrap().flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            let source = std::fs::read_to_string(&path).unwrap();
            for (idx, line) in source.lines().enumerate() {
                // Skip comment lines so this module's own reference to
                // the pre-lift marker in prose (module docs + `Examples`
                // rustdoc) doesn't self-hit. The `//` prefix catches
                // every comment kind (`//`, `///`, `//!`, `////`) per
                // the same convention `success_step.rs::no_command_module_still_spells_raw_info_success`
                // established.
                let trimmed = line.trim_start();
                if trimmed.starts_with("//") {
                    continue;
                }
                if line.contains(&marker) {
                    offenders.push((path.clone(), idx + 1, line.to_string()));
                }
            }
        }
        assert!(
            offenders.is_empty(),
            "commands/*.rs modules still spell the pre-lift twelve-argument \
             `push::execute(...)` stanza (marker fingerprint: {marker:?}); \
             route through `crate::commands::cluster_overlay_release_push_step::\
             push_release_image_amd64_auto_tag` instead:\n{offenders:#?}",
        );
    }

    // Positive-delegation shield: each pre-lift consumer module still
    // routes through the typed primitive at least once. Without this,
    // a future workflow rewrite that drops the "Push Image" step
    // entirely (or renames the primitive without re-pointing a caller)
    // would leave the negative marker-comment shield satisfied by
    // absence rather than by delegation. Pin the positive shape
    // explicitly per the sibling-writer discipline
    // `crate::step_header::every_prelift_module_forwards_through_announce_step_header`
    // established.
    #[test]
    fn every_prelift_module_forwards_through_push_release_image_amd64_auto_tag() {
        let commands_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src")
            .join("commands");
        let expected_forwarder =
            "cluster_overlay_release_push_step::push_release_image_amd64_auto_tag";
        for module in ["kenshi.rs", "kenshi_agent.rs", "nix_builder.rs"] {
            let path = commands_dir.join(module);
            let source = std::fs::read_to_string(&path).unwrap();
            let forwards = source.matches(expected_forwarder).count();
            assert!(
                forwards >= 1,
                "{module} must forward at least once through \
                 `crate::commands::{expected_forwarder}`; found {forwards}. \
                 A dropped call would leave the negative marker-comment \
                 shield satisfied by absence.",
            );
        }
    }

    // Signature shield: pin the exact `(image_path, registry, retries,
    // token) -> Result<()>` arity of the lifted primitive so a future
    // signature drift (adding an `arch` parameter, converting `token`
    // to a required rather than `Option<String>` slot, dropping the
    // `retries` slot in favor of a policy struct) is a compile-fail
    // here at test time rather than a surprise at every one of the
    // three cluster-overlay release flows. The compile-only shape
    // check is the fastest way to see the intent — if the fn type
    // ever diverges from this signature, this file stops compiling
    // and the `cargo test` gate flags the drift.
    #[test]
    fn push_release_image_amd64_auto_tag_signature_stays_stable() {
        // A `fn` pointer coercion pins the exact arity, argument order,
        // ownership shape, and return type of the primitive without
        // running its body. `let _: <T>` is enough to force the type
        // check; the assignment itself is the assertion.
        let _: fn(
            String,
            String,
            u32,
            Option<String>,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = anyhow::Result<()>> + Send>,
        > = |image_path, registry, retries, token| {
            Box::pin(super::push_release_image_amd64_auto_tag(
                image_path, registry, retries, token,
            ))
        };
    }
}
