//! Kenshi operator release operations
//!
//! Release the kenshi operator image with updates to all cluster manifests.
//! Handles both primary and secondary clusters in a single release.

use anyhow::Result;
use tracing::info;

use crate::commands::push;
use crate::commands::release_commit::commit_cluster_overlay_release;

/// Release kenshi operator: push image and update K8s manifests for all clusters
///
/// This handles the complete release workflow:
/// 1. Push image to GHCR with auto-tags (amd64-{sha}, amd64-latest)
/// 2. Update primary cluster kustomization.yaml images[] overlay
/// 3. Update secondary cluster kustomization.yaml images[] overlay
/// 4. Commit and push to git
pub async fn release(
    image_path: String,
    registry: String,
    primary_kustomization: String,
    secondary_kustomization: String,
    retries: u32,
    token: Option<String>,
) -> Result<()> {
    // Step 1: Emit release preamble + resolve git SHA into the canonical
    // `amd64-<sha>` tag via the shared cluster-overlay release primitive.
    let new_tag =
        crate::commands::cluster_overlay_release_preamble::announce_release_start_and_compute_tag(
            "kenshi operator",
            &image_path,
            &registry,
        )
        .await?;

    // Step 2: Push image to GHCR
    crate::step_header::announce_step_header(1, 4, "Push Image");
    push::execute(
        image_path,
        registry.clone(),
        vec![], // tags - will be generated by auto_tags
        true,   // auto_tags
        "amd64".to_string(),
        retries,
        token,
        false,         // push_attic
        String::new(), // attic_cache
        None,          // update_kustomization_path
        false,         // commit_kustomization
    )
    .await?;
    println!();

    // Step 3: Update primary cluster kustomization.yaml images[] overlay
    crate::step_header::announce_step_header(2, 4, "Update primary cluster kustomization");
    update_kustomization_image(&primary_kustomization, &registry, &new_tag).await?;
    println!();

    // Step 4: Update secondary cluster kustomization.yaml images[] overlay
    crate::step_header::announce_step_header(3, 4, "Update secondary cluster kustomization");
    update_kustomization_image(&secondary_kustomization, &registry, &new_tag).await?;
    println!();

    // Step 5: Commit and push
    crate::step_header::announce_step_header(4, 4, "Commit and Push");
    info!("📤 Committing release changes...");
    commit_cluster_overlay_release(
        None,
        "kenshi operator",
        &new_tag,
        &[&primary_kustomization, &secondary_kustomization],
    )
    .await?;

    crate::commands::cluster_overlay_release_postamble::announce_release_complete(
        "kenshi operator",
        &registry,
        &new_tag,
    );

    Ok(())
}

/// Update kustomization.yaml images[] overlay for kenshi
///
/// Finds the kenshi image entry and updates the newTag.
async fn update_kustomization_image(
    kustomization_path: &str,
    registry: &str,
    new_tag: &str,
) -> Result<()> {
    let path = crate::repo::require_existing_labeled(kustomization_path, "Kustomization file")?;

    info!("📝 Updating: {}", kustomization_path);

    // Read content
    let content = crate::repo::read_text_async(path).await?;

    let mut updated = false;
    let mut new_content = String::new();
    let mut in_kenshi_image = false;

    for line in content.lines() {
        // Track if we're in the kenshi image block (but not kenshi-agent)
        if line.contains("name:") && line.contains("kenshi") && !line.contains("kenshi-agent") {
            in_kenshi_image = true;
        }
        // Exit the image block when we hit another image entry
        if in_kenshi_image && line.trim().starts_with("- name:") && !line.contains(registry) {
            in_kenshi_image = false;
        }

        // Update newTag within the kenshi image block
        if in_kenshi_image && line.contains("newTag:") {
            let indent = line.len() - line.trim_start().len();
            let indent_str: String = line.chars().take(indent).collect();
            new_content.push_str(&format!("{}newTag: {}\n", indent_str, new_tag));
            updated = true;
            in_kenshi_image = false; // Done with this block
            info!("   Updated images[] newTag to: {}", new_tag);
        } else {
            new_content.push_str(line);
            new_content.push('\n');
        }
    }

    if !updated {
        anyhow::bail!(
            "No kenshi entry found in images[] in {}",
            kustomization_path
        );
    }

    // Write back
    let final_content = new_content.trim_end().to_string() + "\n";
    crate::repo::write_text_async(path, &final_content).await?;

    info!("   ✅ Kustomization updated");
    Ok(())
}
